version: '3.8'
services:
  auto-trade-coin-gpt:
    build: .
    image: auto-trade-coin-gpt
    container_name: auto-trade-coin-gpt
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      UPBIT_ACCESS_KEY: ${UPBIT_ACCESS_KEY}
      UPBIT_SECRET_KEY: ${UPBIT_SECRET_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_COINBOT_CHANNEL_NAME: ${SLACK_COINBOT_CHANNEL_NAME}
      GPT_MODEL: ${GPT_MODEL}
      MONGO_URI: ${MONGO_URI}
    restart: unless-stopped
    working_dir: /auto_trade_coin
    volumes:
      - ./data:/auto_trade_coin/data
    ports:
      - "8501:8501"
    command: /bin/bash -c "python3 autotrade.py & streamlit run streamlit_app.py"
    networks:
      - wookingwoo-op-bridge

networks:
  wookingwoo-op-bridge:
    external: true
